"use client";

import { useQueryWithStatus } from "@/app/Providers";
import { PageHeader } from "@/components/layoutComponents/page-header";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { EmptyState } from "@/components/ui/empty-state";
import { ErrorState } from "@/components/ui/error-state";
import { Spinner } from "@/components/ui/spinner";
import { useMutation } from "convex/react";
import { Calendar, FileText, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { toast } from "sonner";
import { api } from "../../../convex/_generated/api";
import type { Id } from "../../../convex/_generated/dataModel";

export function BlogsPage() {
  const { data: blogs, isPending, error } = useQueryWithStatus(api.schema.blog.getBlogs);
  const deleteBlog = useMutation(api.schema.blog.deleteBlog);
  const router = useRouter();
  const [showOnlyAutogenerated, setShowOnlyAutogenerated] = useState(false);

  const handleDelete = async (blogId: Id<"blogs">) => {
    try {
      await deleteBlog({ blogId });
      toast.success("Blog deleted successfully");
    } catch (error) {
      console.error("Failed to delete blog:", error);
      toast.error("Failed to delete blog. Please try again.");
    }
  };

  // Filter blogs based on autogenerated toggle
  const filteredBlogs = blogs?.filter((blog) => {
    if (showOnlyAutogenerated) {
      return blog.autoGenerated === true;
    }
    return true;
  });

  if (isPending) {
    return <Spinner centered title="Loading your blog posts..." />;
  }

  if (error) {
    return (
      <div className="flex min-h-screen items-center justify-center p-4">
        <ErrorState
          title="Error Loading Blogs"
          message={error?.message || "Failed to load blogs. Please try again."}
          action={{
            label: "Reload Page",
            onClick: () => window.location.reload(),
          }}
        />
      </div>
    );
  }

  return (
    <div className="container mx-auto max-w-7xl space-y-8 px-4 py-8">
      {/* Header */}
      <PageHeader title="My Blog Posts" description="Manage and view your generated blog posts" />

      {/* Filter Toggle */}
      <div className="flex items-center gap-2">
        <Checkbox id="autogenerated-filter" checked={showOnlyAutogenerated} onCheckedChange={(checked) => setShowOnlyAutogenerated(checked as boolean)} />
        <label htmlFor="autogenerated-filter" className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70">
          Show only auto-generated blogs
        </label>
      </div>

      {blogs && blogs.length === 0 ? (
        <EmptyState
          icon={<FileText className="h-10 w-10" />}
          title="No blog posts yet"
          description="Generate your first blog post from your commits"
          action={{
            label: "Go to Dashboard",
            onClick: () => router.push("/dashboard"),
          }}
        />
      ) : filteredBlogs && filteredBlogs.length === 0 ? (
        <EmptyState icon={<FileText className="h-10 w-10" />} title="No auto-generated blog posts found" description="Try unchecking the filter to see all blogs" />
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {filteredBlogs?.map((blog) => (
            <Card key={blog._id} className="hover:shadow-lg transition-shadow flex flex-col h-full">
              <CardHeader>
                <div className="space-y-2">
                  <CardTitle className="text-lg line-clamp-2">{blog.title}</CardTitle>
                  <div className="flex items-center gap-2 flex-wrap">
                    {blog.autoGenerated && (
                      <Badge variant="secondary" className="text-xs bg-sidebar-accent/10 text-sidebar-accent border-sidebar-accent/20">
                        Auto
                      </Badge>
                    )}
                    <Badge variant={blog.status === "completed" ? "default" : "secondary"}>{blog.status}</Badge>
                  </div>
                  <CardDescription>
                    {blog.platform === "twitter" ? "Twitter/X" : "LinkedIn"} • {blog.commitIds.length} commit
                    {blog.commitIds.length !== 1 ? "s" : ""}
                  </CardDescription>
                </div>
              </CardHeader>
              <CardContent className="flex flex-col flex-1 space-y-4">
                <div className="flex items-center gap-2 flex-wrap text-sm text-muted-foreground min-h-[28px]">
                  <div className="flex items-center gap-2">
                    <Calendar className="h-4 w-4" />
                    <span>{new Date(blog.createdAt).toLocaleDateString()}</span>
                  </div>
                  {blog.options?.toneType && (
                    <Badge variant="outline" className="text-xs">
                      {blog.options.toneType}
                    </Badge>
                  )}
                  {blog.options?.length && (
                    <Badge variant="outline" className="text-xs">
                      {blog.options.length}
                    </Badge>
                  )}
                </div>

                <div className="flex gap-2 mt-auto">
                  <Button size="sm" className="flex-1 bg-accent text-accent-foreground hover:bg-accent/90" onClick={() => router.push(`/blogs/${blog._id}`)}>
                    View Blog
                  </Button>
                  <AlertDialog>
                    <AlertDialogTrigger asChild>
                      <Button size="sm" variant="destructive">
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    </AlertDialogTrigger>
                    <AlertDialogContent>
                      <AlertDialogHeader>
                        <AlertDialogTitle>Delete Blog Post?</AlertDialogTitle>
                        <AlertDialogDescription>This action cannot be undone. This will permanently delete the blog post "{blog.title}".</AlertDialogDescription>
                      </AlertDialogHeader>
                      <AlertDialogFooter>
                        <AlertDialogCancel>Cancel</AlertDialogCancel>
                        <AlertDialogAction onClick={() => handleDelete(blog._id)} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">
                          Delete
                        </AlertDialogAction>
                      </AlertDialogFooter>
                    </AlertDialogContent>
                  </AlertDialog>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
